[phases.setup]
nixPkgs = ["nodejs_22", "nodePackages.pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter @agoraencontrei/database generate",
  "pnpm --filter @agoraencontrei/api build"
]

[start]
cmd = "node apps/api/dist/server.js"
